version: '3.8'

services:
  database:
    image: postgres:16.1-alpine3.18
    container_name: pg-docker
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: module1
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - app-network

  app:
    deploy:
      resources:
        limits:
          cpus: "2.0"    # Максимум  CPU
          memory: "1G" # Максимум  RAM
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aviation-app
    restart: always
    depends_on:
      - database
    environment:
      DB_URL: jdbc:postgresql://database:5432/module1
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SPRING_SERVER_TOMCAT_MAX_THREADS: 200
      HIBERNATE_SHOW_SQL: false
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data: