fixedRate.in.milliseconds=1000
statisticsservice.infostring=LINES
statistics.service=console2000

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/avia_db
spring.datasource.username=avia_user
spring.datasource.password=avia_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JDBC
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none