server.port=8081
spring.application.name=availability-service

# ????????? RestTemplate
rest.template.connection-timeout=5000
rest.template.read-timeout=5000

# Cache configuration
cache.stats.print.interval=30000
cache.ttl=3600000

# Observability
statistics.observability=true
observability.intervals=10,30,60
service.statistic.observability.delay=5000

# Redis
spring.redis.host=${REDIS_HOST:redis-internal}
spring.redis.port=${REDIS_PORT:6379}
spring.redis.timeout=5000

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5000
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.configs.default.slowCallRateThreshold=50
resilience4j.circuitbreaker.configs.default.slowCallDurationThreshold=2s

# Retry
resilience4j.retry.configs.default.maxAttempts=3
resilience4j.retry.configs.default.waitDuration=500ms