server.port=8081
spring.application.name=availability-service

# ????????? RestTemplate
rest.template.connection-timeout=5000
rest.template.read-timeout=5000

# Cache configuration
cache.stats.print.interval=30000
cache.ttl=3600000

# Observability
statistics.observability=true
observability.intervals=10,30,60
service.statistic.observability.delay=5000

# Retry configuration
resilience4j.retry.instances.coreServiceRetry.max-attempts=5
resilience4j.retry.instances.coreServiceRetry.wait-duration=5s
resilience4j.retry.instances.coreServiceRetry.retry-exceptions=org.springframework.web.reactive.function.client.WebClientResponseException

# Circuit Breaker configuration
resilience4j.circuitbreaker.instances.coreServiceCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.coreServiceCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.coreServiceCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.coreServiceCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.coreServiceCircuitBreaker.wait-duration-in-open-state=30s

# WebClient timeouts (??? Additional Service)
web.client.connect-timeout=5s
web.client.read-timeout=10s
web.client.response-timeout=10s

service.scheduler.core.crash.delay=20000