version: '3.8'

services:
  database:
    image: postgres:16.1-alpine3.18
    container_name: pg-docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zandb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zandb"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy

  crud-service:
    build:
      context: ./crud-service
      dockerfile: Dockerfile
    container_name: aviation-crud-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/zandb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_ENABLED: "true"  # Добавьте эту строку
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"  # И эту
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy

  availability-service:
    build:
      context: ./availability-service
      dockerfile: Dockerfile
    container_name: availability-service
    environment:
      CRUD_SERVICE_URL: "http://crud-service:8080"
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - crud-service

networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
  pgadmin_data: