apiVersion: v1
kind: Secret
metadata:
  name: aviation-secrets
  namespace: var6
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # Замените на реальный пароль в base64
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=  # Тот же пароль
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: var6
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJMZW9wb2xkcHQiLCJwYXNzd29yZCI6Ij>  # Замените на ваш конфиг Docker Hub